language: r
cache: packages
sudo: required

apt_packages:
      - libgsl0-dev # for topicmodels
      - libxml2-dev # for XML, a dependency of quanteda

r_binary_packages:
      - XML # not sure why XML is not getting installed without this

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
